definitions:
  handlers.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  handlers.userResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
  model.User:
    properties:
      email:
        type: string
      fullName:
        type: string
      isActive:
        type: boolean
      username:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
  description: Your API Description
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Your API Title
  version: "1.0"
paths:
  /api/v1/users/:
    get:
      description: Return a list of all users from the database
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.userResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Return a list of all users from the database
      tags:
      - Users
swagger: "2.0"
